name: Pre-release on Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libssl-dev

    - name: Build
      run: cargo build --verbose --release

    - name: Run tests
      run: cargo test --verbose
    
    - name: rename executable
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv -v ./target/release/ollama_load_balancer ./ollama_load_balancer_linux
          echo "exec_path=./ollama_load_balancer_linux" >> $GITHUB_ENV
        fi
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          mv -v ./target/release/ollama_load_balancer ./ollama_load_balancer_macos
          echo "exec_path=./ollama_load_balancer_macos" >> $GITHUB_ENV
        fi
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv -v ./target/release/ollama_load_balancer.exe ./ollama_load_balancer_windows.exe
          echo "exec_path=./ollama_load_balancer_windows.exe" >> $GITHUB_ENV
        fi
    - name: Pre-Release
      uses: softprops/action-gh-release@v2
      with:
        files: $GITHUB_ENV.exec_path
        tag_name: Pre-release