name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libssl-dev

    - name: Build
      run: cargo build --verbose --release

    - name: Run tests
      run: cargo test --verbose
